# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'protoype-firebase-authentication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
# Pods for protoype-firebase-authentication


  target 'protoype-firebase-authenticationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'protoype-firebase-authenticationUITests' do
    # Pods for testing
  end

end
